[tool.semantic_release]
version_source = "commit"
version_variables = ["setup.py:__version__"]
branch = "master"
changelog_file = "CHANGELOG.md"
build_command = "pip install build && python -m build"

[tool.semantic_release.release_groups]
develop = ["master"]

[tool.semantic_release.branches.master]
match = "master"
prerelease = false

[tool.semantic_release.publish]
upload_to_repository = true