name: Release

on:
  push:
    branches:
      - master # master 브랜치에 push(머지)될 때 실행

permissions:
  contents: write # GitHub 태그 생성 & 커밋 푸시 권한

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 전체 Git 기록을 가져와야 버전 계산 가능

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-semantic-release build

      - name: Run semantic-release
        env:
          GH_TOKEN: ${{ secrets.ENV_GITHUB_TOKEN }} # GitHub에서 자동 제공하는 권한
          PYPI_TOKEN: ${{ secrets.ENV_PYPI_API_TOKEN }} # PyPI 업로드를 위한 토큰
        run: |
          semantic-release version
          semantic-release publish
